---
# title: Seminario de Estadística I - Aprendizaje Estadístico Automatizado
# subtitle: Tarea 2A - Selección de variables, bootstrap y aprendizaje no supervisado
# author: |
#   | Johan Jesús González Navarrete
#   | Andrés Limón Cruz
#   | Luis Brayan López Canché
#   | Jorge Alberto Herrera León
# date: "`r format(Sys.Date(), '%d de %B del %Y')`"
output: 
  bookdown::pdf_document2:
    number_sections: no
    toc: no
    highlight: tango
    includes:
      in_header: Auxiliares/preambulo.tex
      before_body: Auxiliares/portada.tex
      after_body: null
geometry: margin=2.5cm
decoding: UTF-8
---

```{r setup, include=FALSE}
rm(list = ls(all.names = TRUE))
gc()
knitr::opts_chunk$set(
	error = F,
	fig.align = "center",
	fig.dim = c(5, 3),
	message = FALSE,
	warning = FALSE,
	echo = FALSE
)


#Cargamos nuestras librerías
library(tidyverse)
library(forecast)
library(GGally)
#Estilo global de gráficos
theme_set(theme_minimal())

#Paleta de colores en hexadecimal:
PALETA <- c("#007bff","#ff7f0e","#2ca02c","#d62728","#9467bd","#0012b5ff","#ca5e00ff","#1b5f1bff","#901b1bff","#583379ff")
```

## \href{Ejercicios/Ejercicio1.rmd}{Predicción en el caso continuo}
```{r, child = "Ejercicios/Ejercicio1.rmd"}

```


## \href{Ejercicios/Ejercicio2.rmd}{Clasificación supervisada}
```{r, child = "Ejercicios/Ejercicio2.rmd"}

```



